# Generated by Django 4.2.16 on 2024-09-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_post_liked_by_alter_post_posted_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followed_by',
        ),
        migrations.AddField(
            model_name='post',
            name='poster_name',
            field=models.TextField(default='bob'),
            preserve_default=False,
        ),
    ]
