# Generated by Django 4.2.16 on 2024-09-26 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_remove_post_liked_by_user_liked_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='posts',
        ),
    ]
