# Generated by Django 4.2.16 on 2024-09-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_user_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='liked_posts',
        ),
        migrations.AddField(
            model_name='user',
            name='liked_posts',
            field=models.ManyToManyField(to='network.post'),
        ),
    ]
