# Generated by Django 4.2.16 on 2024-09-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_user_liked_posts_user_liked_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liked_posts',
            field=models.ManyToManyField(related_name='likes', to='network.post'),
        ),
    ]
