# Generated by Django 4.2.16 on 2024-09-26 22:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_user_liked_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='watching',
        ),
        migrations.AddField(
            model_name='user',
            name='watching',
            field=models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
