# Generated by Django 5.0.7 on 2024-08-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, choices=[('Fashion', 'Fashion'), ('Toys', 'Toys'), ('Gifts', 'Gifts'), ('Computers', 'Computers'), ('Decorations', 'Decorations'), ('Cars', 'Cars'), ('Misc.', 'Misc.'), ('Other', 'Other')], max_length=20),
        ),
    ]
