# Generated by Django 5.0.7 on 2024-07-23 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passenget'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passenget',
            new_name='Passenger',
        ),
    ]
